---
title: "蕎麥 老化基因分析"
author: "Jade.Hou"
date: "2017年8月8日"
output: html_document
---

***

> Set working dictionary and read file
```{r}
# set working dictionary
setwd("c:/Users/Jade.Hou/Desktop/microarray")

library(varhandle)

#read buckwheat data
buckwheat = read.csv("C:/Users/Jade.Hou/Desktop/microarray/R1_data/buckwheat.csv", header = T)

```


***

> PINK1 Expression
```{r, fig.width = 10, fig.height = 6}
#PINK1 log2 ratio
b25_6hr <- unfactor(buckwheat[12979, 16])
b25_24hr <- unfactor(buckwheat[12979, 17])
b25_48hr <- unfactor(buckwheat[12979, 18])

b50_6hr <- unfactor(buckwheat[12979, 19])
b50_24hr <- unfactor(buckwheat[12979, 20])
b50_48hr <- unfactor(buckwheat[12979, 21])

pink1 = c(b25_6hr, b25_24hr, b25_48hr, b50_6hr, b50_24hr, b50_48hr)

#barplot catlog vs log2 ratio

barplot(pink1, xlab = "Dose", ylab = "log2 Expression Ratio", main = "PINK1", names.arg = c("0.25mg 6hr", "0.25mg 24hr", "0.25mg 48hr", "0.50mg 6hr", "0.50mg 24hr", "0.50mg 48hr"), col = c("lightblue1", "lightskyblue", "deepskyblue", "darkseagreen1", "darkseagreen2", "darkseagreen3"))

```


***

> CCT2(1) Expression
```{r, fig.width = 10, fig.height = 6}
#CCT2 log2 ratio
b25_6hr <- unfactor(buckwheat[10573, 16])
b25_24hr <- unfactor(buckwheat[10573, 17])
b25_48hr <- unfactor(buckwheat[10573, 18])

b50_6hr <- unfactor(buckwheat[10573, 19])
b50_24hr <- unfactor(buckwheat[10573, 20])
b50_48hr <- unfactor(buckwheat[10573, 21])

CCT2 = c(b25_6hr, b25_24hr, b25_48hr, b50_6hr, b50_24hr, b50_48hr)

#barplot catlog vs log2 ratio

barplot(CCT2, xlab = "Dose", ylab = "log2 Expression Ratio", main = "CCT2", names.arg = c("0.25mg 6hr", "0.25mg 24hr", "0.25mg 48hr", "0.50mg 6hr", "0.50mg 24hr", "0.50mg 48hr"), col = c("lightblue1", "lightskyblue", "deepskyblue", "darkseagreen1", "darkseagreen2", "darkseagreen3"))

```


***

> CCT2(2) Expression
```{r, fig.width = 10, fig.height = 6}
#CCT2 log2 ratio
b25_6hr <- unfactor(buckwheat[20987, 16])
b25_24hr <- unfactor(buckwheat[20987, 17])
b25_48hr <- unfactor(buckwheat[20987, 18])

b50_6hr <- unfactor(buckwheat[20987, 19])
b50_24hr <- unfactor(buckwheat[20987, 20])
b50_48hr <- unfactor(buckwheat[20987, 21])

CCT2 = c(b25_6hr, b25_24hr, b25_48hr, b50_6hr, b50_24hr, b50_48hr)

#barplot catlog vs log2 ratio

barplot(CCT2, xlab = "Dose", ylab = "log2 Expression Ratio", main = "CCT2", names.arg = c("0.25mg 6hr", "0.25mg 24hr", "0.25mg 48hr", "0.50mg 6hr", "0.50mg 24hr", "0.50mg 48hr"), col = c("lightblue1", "lightskyblue", "deepskyblue", "darkseagreen1", "darkseagreen2", "darkseagreen3"))

```


***

> CCT5(1) Expression
```{r, fig.width = 10, fig.height = 6}
#CCT5 log2 ratio
b25_6hr <- unfactor(buckwheat[190, 16])
b25_24hr <- unfactor(buckwheat[190, 17])
b25_48hr <- unfactor(buckwheat[190, 18])

b50_6hr <- unfactor(buckwheat[190, 19])
b50_24hr <- unfactor(buckwheat[190, 20])
b50_48hr <- unfactor(buckwheat[190, 21])

CCT5 = c(b25_6hr, b25_24hr, b25_48hr, b50_6hr, b50_24hr, b50_48hr)

#barplot catlog vs log2 ratio

barplot(CCT5, xlab = "Dose", ylab = "log2 Expression Ratio", main = "CCT5", names.arg = c("0.25mg 6hr", "0.25mg 24hr", "0.25mg 48hr", "0.50mg 6hr", "0.50mg 24hr", "0.50mg 48hr"), col = c("lightblue1", "lightskyblue", "deepskyblue", "darkseagreen1", "darkseagreen2", "darkseagreen3"))

```


***

> CCT5(2) Expression
```{r, fig.width = 10, fig.height = 6}
#CCT5 log2 ratio
b25_6hr <- unfactor(buckwheat[22700, 16])
b25_24hr <- unfactor(buckwheat[22700, 17])
b25_48hr <- unfactor(buckwheat[22700, 18])

b50_6hr <- unfactor(buckwheat[22700, 19])
b50_24hr <- unfactor(buckwheat[22700, 20])
b50_48hr <- unfactor(buckwheat[22700, 21])

CCT5 = c(b25_6hr, b25_24hr, b25_48hr, b50_6hr, b50_24hr, b50_48hr)

#barplot catlog vs log2 ratio

barplot(CCT5, xlab = "Dose", ylab = "log2 Expression Ratio", main = "CCT5", names.arg = c("0.25mg 6hr", "0.25mg 24hr", "0.25mg 48hr", "0.50mg 6hr", "0.50mg 24hr", "0.50mg 48hr"), col = c("lightblue1", "lightskyblue", "deepskyblue", "darkseagreen1", "darkseagreen2", "darkseagreen3"))
```

***

> CCT6A Expression
```{r, fig.width = 10, fig.height = 6}
#CCT6A log2 ratio
b25_6hr <- unfactor(buckwheat[3209, 16])
b25_24hr <- unfactor(buckwheat[3209, 17])
b25_48hr <- unfactor(buckwheat[3209, 18])

b50_6hr <- unfactor(buckwheat[3209, 19])
b50_24hr <- unfactor(buckwheat[3209, 20])
b50_48hr <- unfactor(buckwheat[3209, 21])

CCT6A = c(b25_6hr, b25_24hr, b25_48hr, b50_6hr, b50_24hr, b50_48hr)

#barplot catlog vs log2 ratio

barplot(CCT6A, xlab = "Dose", ylab = "log2 Expression Ratio", main = "CCT6A", names.arg = c("0.25mg 6hr", "0.25mg 24hr", "0.25mg 48hr", "0.50mg 6hr", "0.50mg 24hr", "0.50mg 48hr"), col = c("lightblue1", "lightskyblue", "deepskyblue", "darkseagreen1", "darkseagreen2", "darkseagreen3"))

```



> CCT7(1) Expression
```{r, fig.width = 10, fig.height = 6}
#CCT7 log2 ratio
b25_6hr <- unfactor(buckwheat[11545, 16])
b25_24hr <- unfactor(buckwheat[11545, 17])
b25_48hr <- unfactor(buckwheat[11545, 18])

b50_6hr <- unfactor(buckwheat[11545, 19])
b50_24hr <- unfactor(buckwheat[11545, 20])
b50_48hr <- unfactor(buckwheat[11545, 21])

CCT7 = c(b25_6hr, b25_24hr, b25_48hr, b50_6hr, b50_24hr, b50_48hr)

#barplot catlog vs log2 ratio

barplot(CCT7, xlab = "Dose", ylab = "log2 Expression Ratio", main = "CCT7", names.arg = c("0.25mg 6hr", "0.25mg 24hr", "0.25mg 48hr", "0.50mg 6hr", "0.50mg 24hr", "0.50mg 48hr"), col = c("lightblue1", "lightskyblue", "deepskyblue", "darkseagreen1", "darkseagreen2", "darkseagreen3"))
```


> CCT7(2) Expression
```{r, fig.width = 10, fig.height = 6}
#CCT7 log2 ratio
b25_6hr <- unfactor(buckwheat[17579, 16])
b25_24hr <- unfactor(buckwheat[17579, 17])
b25_48hr <- unfactor(buckwheat[17579, 18])

b50_6hr <- unfactor(buckwheat[17579, 19])
b50_24hr <- unfactor(buckwheat[17579, 20])
b50_48hr <- unfactor(buckwheat[17579, 21])

CCT7 = c(b25_6hr, b25_24hr, b25_48hr, b50_6hr, b50_24hr, b50_48hr)

#barplot catlog vs log2 ratio

barplot(CCT7, xlab = "Dose", ylab = "log2 Expression Ratio", main = "CCT7", names.arg = c("0.25mg 6hr", "0.25mg 24hr", "0.25mg 48hr", "0.50mg 6hr", "0.50mg 24hr", "0.50mg 48hr"), col = c("lightblue1", "lightskyblue", "deepskyblue", "darkseagreen1", "darkseagreen2", "darkseagreen3"))
```


> CCT7(3) Expression
```{r, fig.width = 10, fig.height = 6}
#CCT7 log2 ratio
b25_6hr <- unfactor(buckwheat[25379, 16])
b25_24hr <- unfactor(buckwheat[25379, 17])
b25_48hr <- unfactor(buckwheat[25379, 18])

b50_6hr <- unfactor(buckwheat[25379, 19])
b50_24hr <- unfactor(buckwheat[25379, 20])
b50_48hr <- unfactor(buckwheat[25379, 21])

CCT7 = c(b25_6hr, b25_24hr, b25_48hr, b50_6hr, b50_24hr, b50_48hr)

#barplot catlog vs log2 ratio

barplot(CCT7, xlab = "Dose", ylab = "log2 Expression Ratio", main = "CCT7", names.arg = c("0.25mg 6hr", "0.25mg 24hr", "0.25mg 48hr", "0.50mg 6hr", "0.50mg 24hr", "0.50mg 48hr"), col = c("lightblue1", "lightskyblue", "deepskyblue", "darkseagreen1", "darkseagreen2", "darkseagreen3"))
```



> CCT8 Expression
```{r, fig.width = 10, fig.height = 6}
#CCT8 log2 ratio
b25_6hr <- unfactor(buckwheat[17864, 16])
b25_24hr <- unfactor(buckwheat[17864, 17])
b25_48hr <- unfactor(buckwheat[17864, 18])

b50_6hr <- unfactor(buckwheat[17864, 19])
b50_24hr <- unfactor(buckwheat[17864, 20])
b50_48hr <- unfactor(buckwheat[17864, 21])

CCT8 = c(b25_6hr, b25_24hr, b25_48hr, b50_6hr, b50_24hr, b50_48hr)

#barplot catlog vs log2 ratio

barplot(CCT8, xlab = "Dose", ylab = "log2 Expression Ratio", main = "CCT8", names.arg = c("0.25mg 6hr", "0.25mg 24hr", "0.25mg 48hr", "0.50mg 6hr", "0.50mg 24hr", "0.50mg 48hr"), col = c("lightblue1", "lightskyblue", "deepskyblue", "darkseagreen1", "darkseagreen2", "darkseagreen3"))
```