---
title: "龍眼殼 老化基因分析"
author: "Jade.Hou"
date: "2017年8月8日"
output: html_document
---

***

> Set working dictionary and read file
```{r}
# set working dictionary
setwd("c:/Users/Jade.Hou/Desktop/microarray")

library(varhandle)

#read longan_shells data
longan_shells = read.csv("C:/Users/Jade.Hou/Desktop/microarray/R1_data/longan_shells.csv", header = T)

```


***

> PINK1 Expression
```{r, fig.width = 5, fig.height = 6}
#PINK1 log2 ratio
l25_6hr <- unfactor(longan_shells[11508, 13])
l25_48hr <- unfactor(longan_shells[11508, 14])


pink1 = c(l25_6hr, l25_48hr)

#barplot catlog vs log2 ratio

barplot(pink1, xlab = "Dose", ylab = "log2 Expression Ratio", main = "PINK1", names.arg = c("0.25mg 6hr", "0.25mg 48hr"), col = c("lightblue1", "lightskyblue"))
```


***

> CCT2(1) Expression
```{r, fig.width = 5, fig.height = 6}
#CCT2 log2 ratio
l25_6hr <- unfactor(longan_shells[18041, 13])
l25_48hr <- unfactor(longan_shells[18041, 14])


CCT2 = c(l25_6hr, l25_48hr)

#barplot catlog vs log2 ratio

barplot(CCT2, xlab = "Dose", ylab = "log2 Expression Ratio", main = "CCT2", names.arg = c("0.25mg 6hr", "0.25mg 48hr"), col = c("lightblue1", "lightskyblue"))

```



***

> CCT2(2) Expression
```{r, fig.width = 5, fig.height = 6}
#CCT2 log2 ratio
l25_6hr <- unfactor(longan_shells[9238, 13])
l25_48hr <- unfactor(longan_shells[9238, 14])


CCT2 = c(l25_6hr, l25_48hr)

#barplot catlog vs log2 ratio

barplot(CCT2, xlab = "Dose", ylab = "log2 Expression Ratio", main = "CCT2", names.arg = c("0.25mg 6hr", "0.25mg 48hr"), col = c("lightblue1", "lightskyblue"))

```


***

> CCT5(1) Expression
```{r, fig.width = 5, fig.height = 6}
#CCT5 log2 ratio
l25_6hr <- unfactor(longan_shells[19485, 13])
l25_48hr <- unfactor(longan_shells[19485, 14])


CCT5 = c(l25_6hr, l25_48hr)

#barplot catlog vs log2 ratio

barplot(CCT5, xlab = "Dose", ylab = "log2 Expression Ratio", main = "CCT5", names.arg = c("0.25mg 6hr", "0.25mg 48hr"), col = c("lightblue1", "lightskyblue"))

```


***

> CCT5(2) Expression
```{r, fig.width = 5, fig.height = 6}
#CCT5 log2 ratio
l25_6hr <- unfactor(longan_shells[184, 13])
l25_48hr <- unfactor(longan_shells[184, 14])


CCT5 = c(l25_6hr, l25_48hr)

#barplot catlog vs log2 ratio

barplot(CCT5, xlab = "Dose", ylab = "log2 Expression Ratio", main = "CCT5", names.arg = c("0.25mg 6hr", "0.25mg 48hr"), col = c("lightblue1", "lightskyblue"))
```


***

> CCT6A Expression
```{r, fig.width = 5, fig.height = 6}
#CCT6A log2 ratio
l25_6hr <- unfactor(longan_shells[3008, 13])
l25_48hr <- unfactor(longan_shells[3008, 14])


CCT6A = c(l25_6hr, l25_48hr)

#barplot catlog vs log2 ratio

barplot(CCT6A, xlab = "Dose", ylab = "log2 Expression Ratio", main = "CCT6A", names.arg = c("0.25mg 6hr", "0.25mg 48hr"), col = c("lightblue1", "lightskyblue"))

```

***

> CCT7(1) Expression
```{r, fig.width = 5, fig.height = 6}
#CCT7 log2 ratio
l25_6hr <- unfactor(longan_shells[10155, 13])
l25_48hr <- unfactor(longan_shells[10155, 14])


CCT7 = c(l25_6hr, l25_48hr)

#barplot catlog vs log2 ratio

barplot(CCT7, xlab = "Dose", ylab = "log2 Expression Ratio", main = "CCT7", names.arg = c("0.25mg 6hr", "0.25mg 48hr"), col = c("lightblue1", "lightskyblue"))
```

***

> CCT7(2) Expression
```{r, fig.width = 5, fig.height = 6}
#CCT7 log2 ratio
l25_6hr <- unfactor(longan_shells[15635, 13])
l25_48hr <- unfactor(longan_shells[15635, 14])


CCT7 = c(l25_6hr, l25_48hr)

#barplot catlog vs log2 ratio

barplot(CCT7, xlab = "Dose", ylab = "log2 Expression Ratio", main = "CCT7", names.arg = c("0.25mg 6hr", "0.25mg 48hr"), col = c("lightblue1", "lightskyblue"))
```

***

> CCT7(3) Expression
```{r, fig.width = 5, fig.height = 6}
#CCT7 log2 ratio
l25_6hr <- unfactor(longan_shells[28005, 13])
l25_48hr <- unfactor(longan_shells[28005, 14])


CCT7 = c(l25_6hr, l25_48hr)

#barplot catlog vs log2 ratio

barplot(CCT7, xlab = "Dose", ylab = "log2 Expression Ratio", main = "CCT7", names.arg = c("0.25mg 6hr", "0.25mg 48hr"), col = c("lightblue1", "lightskyblue"))
```

***

> CCT8 Expression
```{r, fig.width = 5, fig.height = 6}
#CCT8 log2 ratio
l25_6hr <- unfactor(longan_shells[15878, 13])
l25_48hr <- unfactor(longan_shells[15878, 14])


CCT8 = c(l25_6hr, l25_48hr)

#barplot catlog vs log2 ratio

barplot(CCT8, xlab = "Dose", ylab = "log2 Expression Ratio", main = "CCT8", names.arg = c("0.25mg 6hr", "0.25mg 48hr"), col = c("lightblue1", "lightskyblue"))
```

***

> Upregulate genes
```{r, fig.width = 8, fig.height = 6}
#venn diagram for upregulate genes
library(VennDiagram)
grid.newpage()
draw.pairwise.venn(area1 = 1328, area2 = 374, cross.area = 229, category = c("0.25mg 48hr", "0.25mg 6hr"), lty = rep("blank", 2), fill = c("light blue", "pink"), cat.cex = c(1.2, 1.2), cat.pos = c(0,0))
```

***

> Aging genes (upregulate)

* HTR2A
* CCL2
* CYP1A1
* EDNRB
* FOXG1


***

> Downregulate genes
```{r, fig.width = 8, fig.height = 6}
#venn diagram for upregulate genes
library(VennDiagram)
grid.newpage()
draw.pairwise.venn(area1 = 1862, area2 = 585, cross.area = 305, category = c("0.25mg 48hr", "0.25mg 6hr"), lty = rep("blank", 2), fill = c("light blue", "pink"), cat.cex = c(1.4, 1.4))
```

